/**
 * Drift detection: shared types.
 *
 * A Claim is something the docs platform asserts. Every claim names a master
 * source (the authority) and zero or more restatements (platform pages,
 * mirrored sources, external docs) that assert the same subject. The checker
 * extracts each side's value and compares.
 *
 * A Finding is one detected disagreement or staleness event, routed to an
 * owner resolved from .github/CODEOWNERS.
 */

export type SourceClass =
  "executable" | "structured" | "synced" | "git-prose" | "external";

export type Confidence = "certain" | "likely" | "prompt";

export type ExtractSpec =
  // Parse a Python constants file: resolve a tuple of constant names to
  // their string values. Produces both the constant-name set and the
  // resolved value set.
  | { type: "python-constants"; tuple: string }
  // Apply `pattern` to file text; capture group 1 holds a vocabulary list.
  // `style` controls how tokens are pulled: backticked spans (MDX code),
  // quoted strings, or bare comma/"or"-separated words (prose). If `ordered`
  // is set, sequence matters (compared positionally, not as a set).
  | {
      type: "token-list";
      pattern: string;
      style?: "backticked" | "quoted" | "upper-words" | "bare";
      ordered?: boolean;
    }
  // Apply `pattern` to file text; capture group 1 is searched for one of
  // `options`; the matched option is the extracted value.
  | { type: "keyword-choice"; pattern: string; options: string[] }
  // Extract a datetime string via `pattern` and classify it tz-aware/naive
  // by the presence of an offset or Z suffix.
  | { type: "datetime-tz"; pattern: string }
  // Parse a JSON file and collect every value of `field`, recursively.
  | { type: "json-field"; field: string }
  // Apply `pattern` to file text; capture group 1 holds an indented path
  // listing (a project-structure block). Each line's first token is a path
  // segment; indentation reconstructs the parent directories, producing the
  // asserted repo-relative path set.
  | { type: "path-listing"; pattern: string }
  // Asserts that a repo path exists (e.g. "generated by lib/x.ts").
  | { type: "file-exists" };

export interface SourceSpec {
  /** Repo-relative path, or path under drift/sources/ for mirrors. */
  ref: string;
  class: SourceClass;
  /** Docs route when this source is a platform page, for report readability. */
  page?: string;
  /** How the source asserts: as constant names ("CANCELLED") or values ("cancelled"). */
  form?: "names" | "values";
  /** Whether the assertion claims to be complete. Non-exhaustive lists
   *  ("e.g. X, Y") can still conflict via unknown tokens but are never
   *  flagged for missing items. */
  exhaustive?: boolean;
  extract: ExtractSpec;
}

interface ClaimBase {
  id: string;
  subject: string;
  /** The authoritative source every restatement is compared against. */
  master: SourceSpec;
}

/**
 * Vocabulary: an enumerated set (statuses, classifications). Sources may
 * assert constant names or values, exhaustively ("One of X, Y, Z") or
 * partially ("e.g. X, Y"). Unknown tokens always conflict; missing tokens
 * conflict only on exhaustive assertions.
 */
export interface VocabularyClaim extends ClaimBase {
  kind: "vocabulary";
  assertedBy: SourceSpec[];
}

/**
 * Proposition: a single-valued fact ("start is timezone-naive"). Every
 * source resolves to one choice; disagreement with the master's choice is
 * a finding.
 */
export interface PropositionClaim extends ClaimBase {
  kind: "proposition";
  assertedBy: SourceSpec[];
}

/**
 * Repo-fact: a page asserts something verifiable about this repository
 * ("this page is generated from lib/x.ts"). The check runs against the
 * repo itself; a false assertion is a finding owned by the page.
 */
export interface RepoFactClaim extends ClaimBase {
  kind: "repo-fact";
  /** Human-readable restatement of what the page claims. */
  assertion: string;
  /** The page making the assertion (the disagreeing source if false). */
  page: SourceSpec;
}

/**
 * Repo-paths: a page lists repo paths (a project-structure block). Every
 * asserted path must exist in the working tree; a listed path that does not
 * exist is a finding. There is no document master - the repo itself is the
 * arbiter.
 */
export interface RepoPathsClaim {
  kind: "repo-paths";
  id: string;
  subject: string;
  master?: SourceSpec;
  assertedBy: SourceSpec[];
}

export type Claim =
  VocabularyClaim | PropositionClaim | RepoFactClaim | RepoPathsClaim;

export interface Evidence {
  ref: string;
  page?: string;
  value: string[] | string | boolean | null;
  missing?: string[];
  extra?: string[];
  note?: string;
}

export interface Finding {
  id: string;
  /**
   * Content hash over claim + source ref + observed values. A mute entry
   * keyed on this expires automatically when either side's value changes -
   * the disagreement it describes is then a different finding.
   */
  fingerprint: string;
  claim: string;
  subject: string;
  confidence: Confidence;
  blocking: boolean;
  /** True when listed in docs-platform/drift/mutes.json. */
  muted?: boolean;
  owner: string;
  /** What an agent or maintainer should do about this finding. */
  action: string;
  /** The master's observed value. */
  master: Evidence;
  /** Each disagreeing source and how it differs. */
  evidence: Evidence[];
}

export interface Mute {
  /** Finding fingerprint to suppress. */
  fingerprint: string;
  /** Why this disagreement is accepted, in one sentence. */
  reason: string;
  /** ISO date after which the mute no longer applies. */
  expires?: string;
}
